#ifdef MSG_CONVERT
/**********************************************************************//**
		VeriQC

		MsgConvert Module
*-
@file   RawMsgDecodeIDDefines.h
@author CHC
@date   2023/09/12
@brief

**************************************************************************/
#ifndef _RAWMSG_DECODE_ID_DEFINES_H_
#define _RAWMSG_DECODE_ID_DEFINES_H_

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _RAWMSG_DECODE_ID_E
{
	RAWMSG_DECODE_ID_RANGE_1 = 0,
	RAWMSG_DECODE_ID_RANGE,
	RAWMSG_DECODE_ID_RANGECMP_1,
	RAWMSG_DECODE_ID_RANGECMP,
	RAWMSG_DECODE_ID_GPSEPH,
	RAWMSG_DECODE_ID_GLOEPH,
	RAWMSG_DECODE_ID_GALEPH,
	RAWMSG_DECODE_ID_GALFNAVEPH,
	RAWMSG_DECODE_ID_GALINAVEPH,
	RAWMSG_DECODE_ID_GALRCEDEPH,
	RAWMSG_DECODE_ID_QZSEPH,
	RAWMSG_DECODE_ID_BDSEPH,
	RAWMSG_DECODE_ID_BDSCNAV1EPH,
	RAWMSG_DECODE_ID_BDSCNAV2EPH,
	RAWMSG_DECODE_ID_BDSCNAV3EPH,
	RAWMSG_DECODE_ID_NICEPH,
	RAWMSG_DECODE_ID_BASEOBS,

	/** Huace raw msg */
	RAWMSG_DECODE_ID_GNSSOBS_1,
	RAWMSG_DECODE_ID_GNSSOBS,
	RAWMSG_DECODE_ID_GNSSOBSCMP_1,
	RAWMSG_DECODE_ID_GNSSOBSCMP,
	RAWMSG_DECODE_ID_EPH_GPS,
	RAWMSG_DECODE_ID_EPH_GLO,
	RAWMSG_DECODE_ID_EPH_GAL,
	RAWMSG_DECODE_ID_EPH_GALNAVF,
	RAWMSG_DECODE_ID_EPH_GALNAVI,
	RAWMSG_DECODE_ID_EPH_GALRCED,
	RAWMSG_DECODE_ID_EPH_QZS,
	RAWMSG_DECODE_ID_EPH_BD2,
	RAWMSG_DECODE_ID_EPH_BD3CNAV1,
	RAWMSG_DECODE_ID_EPH_BD3CNAV2,
	RAWMSG_DECODE_ID_EPH_BD3CNAV3,
	RAWMSG_DECODE_ID_EPH_NIC,

	RAWMSG_DECODE_ID_UNBD3EPHEM,
	RAWMSG_DECODE_ID_UNBD2EPHEM,
	RAWMSG_DECODE_ID_UNOBSVM,
	RAWMSG_DECODE_ID_UNOBSVH,
	RAWMSG_DECODE_ID_UNOBSVBASE,
	RAWMSG_DECODE_ID_UNBASEINFO,
	RAWMSG_DECODE_ID_UNGPSEPH,
	RAWMSG_DECODE_ID_UNBD3EPH,
	RAWMSG_DECODE_ID_UNBDSEPH,
	RAWMSG_DECODE_ID_UNGLOEPH,
	RAWMSG_DECODE_ID_UNGALEPH,

	RAWMSG_DECODE_ID_KMDRANGE,
	RAWMSG_DECODE_ID_KMDBDSEPH,
	RAWMSG_DECODE_ID_KMDGPSEPH,
	RAWMSG_DECODE_ID_KMDGALINAVEPH,
	RAWMSG_DECODE_ID_KMDGLOEPH,

	RAWMSG_DECODE_ID_NVBDSCNAV1EPH,
	RAWMSG_DECODE_ID_NVBDSCNAV2EPH,
	RAWMSG_DECODE_ID_NVBDSCNAV3EPH,
} RAWMSG_DECODE_ID_E;

#ifdef __cplusplus
}
#endif

#endif  /** _RAWMSG_DECODE_ID_DEFINES_H_ */

#endif
