#ifdef MSG_CONVERT
/**********************************************************************//**
		VeriQC

		Message Convert Module
*-
@file   MsgConvertDataTypes.h
@author CHC
@date   2023/06/26
@brief

**************************************************************************/
#ifndef _MSG_CONVERT_DATATYPES_H_
#define _MSG_CONVERT_DATATYPES_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdio.h>
#include <stdint.h>
#include "Encoder/RINEX/RINEXDefines.h"
#include "Encoder/RINEX/RINEXEncoder.h"
#include "TimeDefines.h"
#include "Common/GNSSSignal.h"
#include "Decoder/MsgDecodeDefinesEx.h"
#include "BSW/MsgDecoder/MsgDecodeDataTypes.h"

#define MAX_OBS_NUM                     256

#define MAXSIGTYPE                      32
#define MAXPOSHIS                       (512)

#define MAX_RNX_DAT_BUF_LEN             (36 * 1024)
#define MAX_RCV_ID_COUNT                16

#define MAX_RAWMSG_DAT_BUF_LEN          (36 * 1024)

#define MAX_RTCM_DAT_BUF_LEN            (36 * 1024)

#define MAX_RINEX_BUF_LEN               (1024*32)
#define MAX_RAWMSG_BUF_LEN              (1024*32)

enum {
	DATA_OUT_TYPE_RINEX = 0,
	DATA_OUT_TYPE_RAWMSGASCII,
	DATA_OUT_TYPE_BASEOBSASCII,
	DATA_OUT_TYPE_RAWMSGPROCESS,
	DATA_OUT_TYPE_RTCM,
	DATA_OUT_TYPE_RTKPLOT,
	DATA_OUT_TYPE_ASCII,
	DATA_OUT_TYPE_BINARY,

	DATA_OUT_TYPE_MAX,
};

typedef enum _RAW_DATA_TYPE_E
{
	RAW_DATA_TYPE_RTCM3 = 0,
	RAW_DATA_TYPE_RTCM2,
	RAW_DATA_TYPE_RAWMSG_ASCII,
	RAW_DATA_TYPE_RAWMSG_BINARY,
	RAW_DATA_TYPE_HRCX,
	RAW_DATA_TYPE_NMEA,
	RAW_DATA_TYPE_RINEX,

	RAW_DATA_TYPE_NUM_MAX,
} RAW_DATA_TYPE_E;

typedef struct _RINEX_DATA_BUF_T
{
	int ReceiveID;
	unsigned int NavTimeFlag[MAX_RCV_ID_COUNT][MAX_OBS_NUM];
	unsigned int BDSTimeFlag[MAX_RCV_ID_COUNT][MAX_BDS_SAT_NUM][4]; /**< BDS Sat type BDS CNAV1 CNAV2 CNAV3 */
	unsigned int GALTimeFlag[MAX_RCV_ID_COUNT][MAX_GAL_SAT_NUM];
	unsigned int GALTypeTimeFlag[MAX_RCV_ID_COUNT][MAX_GAL_SAT_NUM][3];
	unsigned char GALTgdFlag[MAX_RCV_ID_COUNT][MAX_GAL_SAT_NUM][2];
	double GALTgd[MAX_RCV_ID_COUNT][MAX_GAL_SAT_NUM][2];
	unsigned int BDSJpFlag[MAX_RCV_ID_COUNT][3][MAX_BDS_SAT_NUM]; /**< Code: 00 = reserved; BDS3-JP: 01 = B1C; 10 = B1A; 11 = B3A */
} RINEX_DATA_BUF_T;

typedef enum _MSG_CONVERT_FILE_INDEX_E
{
	MSG_CONVERT_FILE_INDEX_MUTIEPH = 0,

	MSG_CONVERT_FILE_INDEX_START = 1,

	MSG_CONVERT_FILE_INDEX_GPSEPH = MSG_CONVERT_FILE_INDEX_START,
	MSG_CONVERT_FILE_INDEX_GLOEPH,
	MSG_CONVERT_FILE_INDEX_GALEPH,
	MSG_CONVERT_FILE_INDEX_QZSSEPH,
	MSG_CONVERT_FILE_INDEX_BDSEPH,
	MSG_CONVERT_FILE_INDEX_SBASEPH,
	MSG_CONVERT_FILE_INDEX_NICEPH,

	MSG_CONVERT_FILE_EPH_NUM_MAX,

	MSG_CONVERT_FILE_INDEX_BASEOBS = MSG_CONVERT_FILE_EPH_NUM_MAX,
	MSG_CONVERT_FILE_INDEX_REFSTATIONINFO,
	MSG_CONVERT_FILE_INDEX_REFSTATION,
	MSG_CONVERT_FILE_INDEX_BESTPOS_1,
	MSG_CONVERT_FILE_INDEX_BESTPOS,
	MSG_CONVERT_FILE_INDEX_BESTXYZ_1,
	MSG_CONVERT_FILE_INDEX_BESTXYZ,
	MSG_CONVERT_FILE_INDEX_BESTVEL_1,
	MSG_CONVERT_FILE_INDEX_BESTVEL,
	MSG_CONVERT_FILE_INDEX_BESTDOP_1,
	MSG_CONVERT_FILE_INDEX_BESTDOP,
	MSG_CONVERT_FILE_INDEX_BESTSATS_1,
	MSG_CONVERT_FILE_INDEX_BESTSATS,
	MSG_CONVERT_FILE_INDEX_PSRPOS_1,
	MSG_CONVERT_FILE_INDEX_PSRPOS,
	MSG_CONVERT_FILE_INDEX_PSRVEL_1,
	MSG_CONVERT_FILE_INDEX_PSRVEL,
	MSG_CONVERT_FILE_INDEX_RTKPOS_1,
	MSG_CONVERT_FILE_INDEX_RTKPOS,
	MSG_CONVERT_FILE_INDEX_RTKVEL_1,
	MSG_CONVERT_FILE_INDEX_RTKVEL,
	MSG_CONVERT_FILE_INDEX_PPPPOS_1,
	MSG_CONVERT_FILE_INDEX_PPPPOS,
	MSG_CONVERT_FILE_INDEX_MATCHEDPOS_1,
	MSG_CONVERT_FILE_INDEX_MATCHEDPOS,
	MSG_CONVERT_FILE_INDEX_VERSION,

	MSG_CONVERT_FILE_INDEX_RAWSBASFRAME2,
	MSG_CONVERT_FILE_INDEX_GALCNAVRAWPAGE,

	MSG_CONVERT_FILE_INDEX_UPBEATORB,
	MSG_CONVERT_FILE_INDEX_UPBEATCLK,
	MSG_CONVERT_FILE_INDEX_UPBEATCLKHIGH,
	MSG_CONVERT_FILE_INDEX_UPBEATURA,
	MSG_CONVERT_FILE_INDEX_UPBEATPCO,
	MSG_CONVERT_FILE_INDEX_UPBEATCBS,
	MSG_CONVERT_FILE_INDEX_UPBEATPBS,
	MSG_CONVERT_FILE_INDEX_UPBEATFCB,
	MSG_CONVERT_FILE_INDEX_UPBEATIONO,
	MSG_CONVERT_FILE_INDEX_UPBEATTROP,

	MSG_CONVERT_FILE_INDEX_IONUTC,

	MSG_CONVERT_FILE_INDEX_RAWIMUX,
	MSG_CONVERT_FILE_INDEX_RAWIMUX_1,

	MSG_CONVERT_FILE_INDEX_INSPVA,
	MSG_CONVERT_FILE_INDEX_INSPVAX,

	MSG_CONVERT_FILE_INDEX_BDSIONO,

	MSG_CONVERT_FILE_INDEX_RAWRTCMAUX,

	MSG_CONVERT_FILE_INDEX_TIME,

	MSG_CONVERT_FILE_INDEX_ANTENNASTATUS,
	MSG_CONVERT_FILE_INDEX_RXSTATUS,
	MSG_CONVERT_FILE_INDEX_RTCMINSTATUS,

	MSG_CONVERT_FILE_INDEX_MARK1TIME,
	MSG_CONVERT_FILE_INDEX_MARK2TIME,
	MSG_CONVERT_FILE_INDEX_MARK3TIME,
	MSG_CONVERT_FILE_INDEX_MARK4TIME,
	MSG_CONVERT_FILE_INDEX_MARK1POS,
	MSG_CONVERT_FILE_INDEX_MARK2POS,
	MSG_CONVERT_FILE_INDEX_MARK3POS,
	MSG_CONVERT_FILE_INDEX_MARK4POS,

	MSG_CONVERT_FILE_INDEX_SATVIS2,

	MSG_CONVERT_FILE_INDEX_TILTCONFIG,
	MSG_CONVERT_FILE_INDEX_TILTCALIB,

	MSG_CONVERT_FILE_INDEX_JAMPSDDETECT,

	MSG_CONVERT_FILE_INDEX_CPUUSAGE,
	MSG_CONVERT_FILE_INDEX_HEAPUSAGE,
	MSG_CONVERT_FILE_INDEX_TASKUSAGE,

	MSG_CONVERT_FILE_INDEX_LBANDBEAMTABLE,
	MSG_CONVERT_FILE_INDEX_LBANDTRACKSTAT,
	MSG_CONVERT_FILE_INDEX_LBANDRAWFRAME,

	MSG_CONVERT_FILE_INDEX_PPSSTATUS,

	MSG_CONVERT_FILE_INDEX_HEADING,
	MSG_CONVERT_FILE_INDEX_MTDFH,

	MSG_CONVERT_FILE_INDEX_FILTERDBG_1,
	MSG_CONVERT_FILE_INDEX_FILTERDBG,

	MSG_CONVERT_FILE_INDEX_FILELIST,
	MSG_CONVERT_FILE_INDEX_FILESTATUS,
	MSG_CONVERT_FILE_INDEX_FILESYSTEMSTATUS,

	MSG_CONVERT_FILE_INDEX_SPPPFILTER,
	MSG_CONVERT_FILE_INDEX_ANTISPOOFSTATUS,

	/** Huace raw msg */
//	MSG_CONVERT_FILE_INDEX_BASEOBS,
	MSG_CONVERT_FILE_INDEX_BASESTATIONINFO,
	MSG_CONVERT_FILE_INDEX_BASESTATION,
	MSG_CONVERT_FILE_INDEX_BESTP_1,
	MSG_CONVERT_FILE_INDEX_BESTP,
	MSG_CONVERT_FILE_INDEX_BESTECEF_1,
	MSG_CONVERT_FILE_INDEX_BESTECEF,
	MSG_CONVERT_FILE_INDEX_BESTV_1,
	MSG_CONVERT_FILE_INDEX_BESTV,
	MSG_CONVERT_FILE_INDEX_BESTDOPS_1,
	MSG_CONVERT_FILE_INDEX_BESTDOPS,
	MSG_CONVERT_FILE_INDEX_BESTSATINFO_1,
	MSG_CONVERT_FILE_INDEX_BESTSATINFO,
	MSG_CONVERT_FILE_INDEX_SPPP_1,
	MSG_CONVERT_FILE_INDEX_SPPP,
	MSG_CONVERT_FILE_INDEX_SPPV_1,
	MSG_CONVERT_FILE_INDEX_SPPV,
	MSG_CONVERT_FILE_INDEX_RTKP_1,
	MSG_CONVERT_FILE_INDEX_RTKP,
	MSG_CONVERT_FILE_INDEX_RTKV_1,
	MSG_CONVERT_FILE_INDEX_RTKV,
	MSG_CONVERT_FILE_INDEX_PPPP_1,
	MSG_CONVERT_FILE_INDEX_PPPP,
	MSG_CONVERT_FILE_INDEX_MATCHEDP_1,
	MSG_CONVERT_FILE_INDEX_MATCHEDP,
	MSG_CONVERT_FILE_INDEX_VERSIONX,
	MSG_CONVERT_FILE_INDEX_GPSIONO,
	MSG_CONVERT_FILE_INDEX_GPSUTC,
	MSG_CONVERT_FILE_INDEX_IMUOBS_1,
	MSG_CONVERT_FILE_INDEX_IMUOBS,
	MSG_CONVERT_FILE_INDEX_INSSOL,
	MSG_CONVERT_FILE_INDEX_INSSOLX,
	MSG_CONVERT_FILE_INDEX_BD2IONO,
	MSG_CONVERT_FILE_INDEX_BD3IONO,
	MSG_CONVERT_FILE_INDEX_TIMES,
	MSG_CONVERT_FILE_INDEX_DEVICESTATUS,
	MSG_CONVERT_FILE_INDEX_EVENT1T,
	MSG_CONVERT_FILE_INDEX_EVENT2T,
	MSG_CONVERT_FILE_INDEX_EVENT3T,
	MSG_CONVERT_FILE_INDEX_EVENT4T,
	MSG_CONVERT_FILE_INDEX_EVENT1P,
	MSG_CONVERT_FILE_INDEX_EVENT2P,
	MSG_CONVERT_FILE_INDEX_EVENT3P,
	MSG_CONVERT_FILE_INDEX_EVENT4P,
	MSG_CONVERT_FILE_INDEX_SATINVIEW,
	MSG_CONVERT_FILE_INDEX_LBDBEAMSTAT,
	MSG_CONVERT_FILE_INDEX_LBDTRACKINFO,
	MSG_CONVERT_FILE_INDEX_LBDRAWFRAME,
	MSG_CONVERT_FILE_INDEX_DANTHEADING,
	MSG_CONVERT_FILE_INDEX_MTDDANTHEADING,
	MSG_CONVERT_FILE_INDEX_SFLTPPPP,
	MSG_CONVERT_FILE_INDEX_UVNAV,

	MSG_CONVERT_FILE_INDEX_CTCDG,

	MSG_CONVERT_FILE_NUM_MAX,
} MSG_CONVERT_FILE_INDEX_E;

typedef struct _SINGLE_OBS_CONVERT_DATA_T
{
	RINEX_OBS_OPT_T RINEXObsOpt;
	RINEX_EPH_OPT_T RINEXEphOpt;
	RINEX_OBS_HEADER_T RINEXObsHeader;
	RINEX_EPH_HEADER_T RINEXEphHeader;
	RINEX_GEPH_HEADER_T RINEXGEphHeader;/*< The ephemeris head of GLONASS */

	UTC_TIME_T TimeStartHistory[MAXPOSHIS];
	UTC_TIME_T TimeEndHistory[MAXPOSHIS];
	UTC_TIME_T OldTime;

	char OutputObsFilePath[512];

	unsigned int SysSigType[TOTAL_EX_GNSS_SYSTEM_NUM][MAXSIGTYPE];

	int Rece;
	double TimeInt;
	int DiffPos;

	double PosHistory[MAXPOSHIS][3];
	int MaxPoshis;
	int PosHistoryNum;
	double PosHistoryBuf[3];

	FILE* RinexObsFileFp;
	char RinexObsFileFpFlag;

	FILE* RinexNavFileFp[MSG_CONVERT_FILE_EPH_NUM_MAX];
	char RinexNavFileFpFlag[MSG_CONVERT_FILE_EPH_NUM_MAX];

	FILE* FpObsSatCountOutP;
} SINGLE_OBS_CONVERT_DATA_T;

typedef struct _RINEX_MULTI_CONVERT_DATA_T
{
	RINEX_OBS_OPT_T RINEXObsOpt;
	RINEX_EPH_OPT_T RINEXEphOpt;
	RINEX_OBS_HEADER_T RINEXObsHeader;
	RINEX_EPH_HEADER_T RINEXEphHeader;
	RINEX_GEPH_HEADER_T RINEXGEphHeader;/*< The ephemeris head of GLONASS */

	UTC_TIME_T TimeStartHistory[MAXPOSHIS];
	UTC_TIME_T TimeEndHistory[MAXPOSHIS];
	UTC_TIME_T OldTime;

	char OutputObsFilePath[512];

	unsigned int SysSigType[TOTAL_EX_GNSS_SYSTEM_NUM][MAXSIGTYPE];

	int Rece;
	double TimeInt;
	int DiffPos;

	double PosHistory[MAXPOSHIS][3];
	int MaxPoshis;
	int PosHistoryNum;
	double PosHistoryBuf[3];

	FILE* RinexObsFileFp;
	char RinexObsFileFpFlag;

	FILE* RinexNavFileFp[MSG_CONVERT_FILE_EPH_NUM_MAX];
	char RinexNavFileFpFlag[MSG_CONVERT_FILE_EPH_NUM_MAX];

	FILE* FpObsSatCountOutP;
} RINEX_MULTI_CONVERT_DATA_T;

typedef struct _MSG_CONVERT_DATA_T
{
	int RawObsDataType;
	SINGLE_OBS_CONVERT_DATA_T GlobalObsConvertData;
	SINGLE_OBS_CONVERT_DATA_T SingleObsConvertData[RAW_OBS_DATA_TYPE_NUM_MAX];

	RINEX_OBS_OPT_T RINEXObsOpt;
	RINEX_EPH_OPT_T RINEXEphOpt;
	RINEX_OBS_HEADER_T RINEXObsHeader;
	RINEX_EPH_HEADER_T RINEXEphHeader;
	RINEX_GEPH_HEADER_T RINEXGEphHeader;/*< The ephemeris head of GLONASS */

	RINEX_INFO_T RinexInfo;
	RINEX_INFO_T RinexMultiInfo[RINEX_GROUP_NUM_MAX];

	RINEX_DATA_BUF_T RINEXDataBuf;

	MSG_BUF_T EncodeDataBuf;

	UTC_TIME_T TimeStartHistory[MAXPOSHIS];
	UTC_TIME_T TimeEndHistory[MAXPOSHIS];
	UTC_TIME_T OldTime;

	FILE* RawFp;
	FILE* FpRawMsgOutP;
	char FpRawMsgOutPFlag;

	FILE* FpOutO;
	FILE* FpOutP[MSG_CONVERT_FILE_NUM_MAX];
	char FpOutPFlag[MSG_CONVERT_FILE_NUM_MAX];

	FILE* LbandRawFrameFpOutP[10];
	char LbandRawFrameFpOutPFlag[10];
	char LbandRawFrameName[10][64];
	unsigned int LbandRawFrameCount;

	FILE* FpDebugInfoOutP;
	FILE* FpBaseObsSatCountOutP;

	FILE* FpRTKPlotOutP;
	char FpRTKPlotOutPFlag;

	FILE* FpRTCMOutP;

	FILE* RinexFileFp[RINEX_FILE_INDEX_NUM];
	char RinexFileFpFlag[RINEX_FILE_INDEX_NUM];

	unsigned int RinexMultiFileNum;
	FILE* RinexMultiFileFp[RINEX_GROUP_NUM_MAX][RINEX_FILE_INDEX_NUM];
	char RinexMultiFileFpFlag[RINEX_GROUP_NUM_MAX][RINEX_FILE_INDEX_NUM];

	RINEX_MULTI_CONVERT_DATA_T RinexMultiConvertData;

	unsigned int SysSigType[TOTAL_EX_GNSS_SYSTEM_NUM][MAXSIGTYPE];

	char OutDir[256];
	char PureName[128];
	int Rece;
	double TimeInt;
	int PrintfNumLimit;
	int DiffPos;
	int DecodeObsNum;

	double PosHistory[MAXPOSHIS][3];
	int MaxPoshis;
	int AllFreqFlag;
	UTC_TIME_T RTCMTime;
	UTC_TIME_T HRCXTime;
	int PosHistoryNum;
	double PosHistoryBuf[3];
	int InputDataType;
	int DataOutType;

	int ObsEpochNum;

	int EPHSameIndex;
	unsigned char EPHSameFlag[4096 * 2][24];
	unsigned char SatTime[24];

	GNSS_OBS_SAT_DATA_T ObsSatData;

	unsigned int ObsFreqFilterEnable;	/**< 0: not filter, other: filter */
	unsigned int ObsFreqFilter[7];		/**< 0xFFFFFFFF: system freq no filter, other:bit0-bit31: range data signal type, 0:filter, 1:no filter */

	unsigned int ObsSatFilterEnable;	/**< 0: not filter, other: filter */
	UINT64 ObsSatFilter[7];				/**< 0xFFFFFFFFFFFFFFFF: system satellite no filter, other:bit0-bit63: satellite1-64, 0:filter, 1:no filter */
} MSG_CONVERT_DATA_T;

#ifdef __cplusplus
}
#endif

#endif  /** _MSG_CONVERT_DATATYPES_H_ */
#endif
